Build a basic mock OEIS
numberscope/backscope pull request #105
Opened 2023-11-15 23:04 UTC by Vectornaut

We need a mock OEIS to test Backscope's response to OEIS behavior that we can't or shouldn't be replicate at will using real OEIS API calls. Examples include throttling and site outages.

This pull request changes the Backscope app to enable mock OEIS tests:
- Make the OEIS request URL a configuration parameter that `create_app` can set.
- Add timeouts to all OEIS requests. (This is meant to prevent mock OEIS tests from hanging.)

It also starts building a mock OEIS:
- Write the basic outline of a mock OEIS, not yet using it for any genuine tests.
- Write a basic example of a test which uses the mock OEIS.
  - This test should pass as long as all others pass and the mock OEIS is working, so it serves as a test of the mock OEIS itself.
  - Eventually, we should probably write an abstract mock OEIS test, in the spirit of `AbstractEndpointTest`. Then we go back and simplify `TestMockOEIS`.

2023-11-16 04:32 UTC, katestange commented
So to test this, should I simply pull and then `flask run` and `flask test`?  Or is there something else I ought to do?

2023-11-16 04:39 UTC, Vectornaut commented
Since the mock OEIS is a Flask application, you can launch it manually by calling
```bash
flask --app mock_oeis run
```
and interact with it through a browser! For example, the `ready` endpoint should be at `http://localhost:5000/ready`.

2023-11-16 04:45 UTC, katestange commented
Doing `flask test` looks like it is doing what it should, it gives:
```
.s. * Serving Flask app 'mock_oeis'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5001
Press CTRL+C to quit
127.0.0.1 - - [15/Nov/2023 21:43:29] "GET /ready HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2023 21:43:29] "GET /test HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2023 21:43:29] "GET /A153080/b153080.txt HTTP/1.1" 200 -
127.0.0.1 - - [15/Nov/2023 21:43:29] "GET /search?q=A153080&fmt=json HTTP/1.1" 200 -
.
----------------------------------------------------------------------
Ran 4 tests in 0.782s

OK (skipped=1)
```

2023-11-16 04:55 UTC, katestange commented
I was able to succeed playing around with the `/ready` and `/test` and `/<oeis_id>/<filename>` endpoints and observe what I understand to the be the expected behaviour.  But the `/search` endpoint returns 400 bad request.

2023-11-16 04:58 UTC, katestange commented on flaskr/nscope/test/test_mock_oeis.py
> +    'values': {
I'm just curious why these values are here?  The mock OEIS server at the moment doesn't respond to this `api/get_oeis_values/...` endpoint.

2023-11-16 05:00 UTC, katestange commented
> I was able to succeed playing around with the `/ready` and `/test` and `/<oeis_id>/<filename>` endpoints and observe what I understand to the be the expected behaviour. But the `/search` endpoint returns 400 bad request.

Also, should there be some documentation of these endpoints included in this PR?  (I don't know whether there should; I'm just bringing it up.)

2023-11-16 05:27 UTC, Vectornaut commented
> But the `/search` endpoint returns 400 bad request.

What search query are you using? The mock OEIS uses the same query URL format as the real one. You should get a 400 response unless you request results in JSON format, and your query is one of these:
- A153080
- A321580
- id:A153080
- id:A321580

Here's an example of a [real OEIS search URL](https://oeis.org/search?q=A153080&fmt=json) that should also work on the mock OEIS.

I tried to return a helpful error message along with the 400, but apparently that's not working! At least, I can't see the error message anywhere in the Firefox request inspector.

Seeing how far from apparent this all is, I agree that some documentation might be a good idea, even though the mock OEIS isn't used in genuine tests yet. I could add a section to the "Running tests" page.

2023-11-16 18:40 UTC, katestange commented
> Here's an example of a [real OEIS search URL](https://oeis.org/search?q=A153080&fmt=json) that should also work on the mock OEIS.

Oh!  That's how search works!  I didn't know that, I was just trying `/search`

> I tried to return a helpful error message along with the 400, but apparently that's not working! At least, I can't see the error message anywhere in the Firefox request inspector.

Nope, didn't see anything.

> Seeing how far from apparent this all is, I agree that some documentation might be a good idea, even though the mock OEIS isn't used in genuine tests yet. I could add a section to the "Running tests" page.

Yeah, I think just to test it out, I needed some documentation guidance ;)

2023-11-16 19:27 UTC, gwhitney commented
I agree that a brief section at the end of doc/tests.md recording the fact that the mock_oeis exists and how it can be used to write tests would be a good addition to this PR before it is merged.

2023-11-22 19:34 UTC, Vectornaut commented
Just added documentation in `doc/tests.md` and the new file `doc/mock-oeis.md`. It's mostly copied from this conversation.

2023-11-23 16:40 UTC, katestange requested changes
It works as advertised on my machine!

2023-11-23 16:40 UTC, katestange commented on doc/mock-oeis.md
> +### Available endpoints
Should this also document `/test` and `/ready`?

2023-11-28 19:31 UTC, Vectornaut commented on doc/mock-oeis.md
> +### Available endpoints
Oops—yes, it should. I've documented `/ready` and eliminated `/test`, since we can now test the mock OEIS by calling an actual OEIS endpoint.

2023-11-28 19:36 UTC, Vectornaut commented on flaskr/nscope/test/test_mock_oeis.py
> +    'values': {
Does this still look weird to you? I think this expected JSON is now used, and working, in `test_endpoint`.

2023-11-29 21:54 UTC, Vectornaut commented on flaskr/nscope/test/test_mock_oeis.py
> +    'values': {
Verbally confirmed that this is resolved!

2023-11-29 22:21 UTC, katestange approved these changes
looks good now!  tested it one more time

2023-11-29 22:21 UTC, merged