Log request issues
numberscope/backscope pull request #111
Opened 2024-01-16 20:17 UTC by Vectornaut

This PR sets up a system to log requests that go wrong. This involves several smaller changes.

#### Logging

- Switches to [`structlog`](https://www.structlog.org) for all explicit logging. This makes it easy to write JSON logs that include all the response data from problematic requests, while also writing summary logs to standard output.
  - To keep built-in logs working, I store the structured logger in a new `structlogger` attribute of the app, leaving the default `logger` attribute as it is.
  - **To do:** once the commit hash endpoint is working, would it make sense to log a startup message with the current commit hash every time `create_app` runs? This might make it easier to see which version of the software other log entries are coming from.
- Adds an [`oeis_get`](../../../vectornaut/backscope/blob/logbad/flaskr/nscope/views.py) wrapper for OEIS requests, which automatically logs any problems.

#### Testing

- Adds a [unit test](../../../vectornaut/backscope/blob/logbad/flaskr/nscope/test/test_logging.py) that just writes a log message and checks whether that works.
- Revises the end-to-end [lookup error test](../../../vectornaut/backscope/blob/logbad/flaskr/nscope/test/test_lookup_errors.py) to comfirm that the failed request is logged as expected.
  - To accomplish this, adds a way to verify log messages in the [abstract request test](../../../vectornaut/backscope/blob/logbad/flaskr/nscope/test/abstract_endpoint_test.py)

2024-04-09 17:55 UTC, katestange requested changes
Maybe this needs some documentation (markdown), like where are logs written to, and whether anything needs to be done to enable logging, and what is logged?  Other than that, it runs fine on my system and I've pasted in the `flask test` output for the unit test, which looks like it was ok.  I can verify that it creates `api.log` on my system if it doesn't exist, although I wasn't sure how to cause it to log something in there (I played with some sequences and nothing was logged although in the shell it showed various successful API calls).

2024-04-09 17:55 UTC, katestange commented on flaskr/nscope/test/test_logging.py
> +class LoggingTest(unittest.TestCase):
Running `flask test` on my system resulted in the following output:
```
.scurrent structured logger type:  <class 'structlog._config.BoundLoggerLazyProxy'>
current structured logger type:  <class 'structlog._config.BoundLoggerLazyProxy'>
..current structured logger type:  <class 'structlog._config.BoundLoggerLazyProxy'>
. * Serving Flask app 'mock_oeis'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5001
Press CTRL+C to quit
127.0.0.1 - - [09/Apr/2024 11:41:54] "GET /ready HTTP/1.1" 200 -
current structured logger type:  <class 'structlog._config.BoundLoggerLazyProxy'>
127.0.0.1 - - [09/Apr/2024 11:41:54] "GET /A153080/b153080.txt HTTP/1.1" 200 -
current structured logger type:  <class 'structlog._config.BoundLoggerLazyProxy'>
127.0.0.1 - - [09/Apr/2024 11:41:55] "GET /search?q=A153080&fmt=json HTTP/1.1" 200 -
.
----------------------------------------------------------------------
Ran 6 tests in 1.128s

OK (skipped=1)
```

2024-04-09 17:55 UTC, katestange commented on flaskr/nscope/views.py
> +    ##r = requests.get(match_url).json()
why is some stuff just commented out?

2024-04-11 08:03 UTC, Vectornaut commented on flaskr/nscope/views.py
> +    ##r = requests.get(match_url).json()
Whoops, all that stuff is old code I meant to remove! I'll go through and clean it up on Thursday.

2024-04-11 08:10 UTC, Vectornaut commented on flaskr/nscope/test/test_logging.py
> +class LoggingTest(unittest.TestCase):
Good idea! I've started a documentation page, [`doc/logging.md`](https://github.com/Vectornaut/backscope/blob/logbad/doc/logging.md). I still need to describe:

- How to intentionally generate a log entry.
- Which tests involve the logging system.
- How the verbosity level differs depending on the environment and whether you're reading the console or the log files.

If there are other topics you'd find useful, let me know.

2024-04-11 08:19 UTC, Vectornaut commented
Updates:
- Brought the PR up to date with the new commit hash endpoint code.
- Made each "request issue" log entry include a dump of the request-response conversation, like it's supposed to. (I thought I'd done this already, but I accidentally told the logger to throw away the dump instead of including it.)

2024-04-11 15:37 UTC, gwhitney commented on flaskr/nscope/test/test_logging.py
> +class LoggingTest(unittest.TestCase):
- How are logs aged (i.e. is api.log.5 always the oldest)? How are they limited in size/chronological period? If something goes haywire and starts producing a gazillion messages, does that push out all the earlier logging entries so we lose the record of the onset of the craziness, which can sometimes be very useful?
- It seems the log files go within the package directory structure. Presuming so, they need to be added to .gitignore so nobody inadvertently commits a log file.

2024-04-11 21:03 UTC, katestange reviewed
Let me know when you want me to test it all again.

2024-04-11 21:13 UTC, gwhitney commented
I just pulled the current version of this PR and ran its tests, and the test of getting a nonexistent sequence failed. So @Vectornaut I am guessing this is not ready for further review and for building on to get a head start on #77? Let us know when you think it's stable enough. Thanks!

2024-04-11 23:03 UTC, Vectornaut commented
> I just pulled the current version of this PR and ran its tests, and the test of getting a nonexistent sequence failed

Oh, right—I fixed the bug that was leaving HTTP response dumps out of log entries, but didn't update the expected log output to include a response dump. The easiest test (comparing against a fixed expected log message) could stop working if the OEIS changes its 404 page. Is that easy test good enough for now?

2024-04-12 00:25 UTC, gwhitney commented
> > I just pulled the current version of this PR and ran its tests, and the test of getting a nonexistent sequence failed
> 
> Oh, right—I fixed the bug that was leaving HTTP response dumps out of log entries, but I haven't yet updated the test's expected log entry to include a response dump. The easiest test (comparing against a fixed expected log message) would stop working if the OEIS changes its 404 page. Is that easy test good enough for now?

I think definitely so. The OEIS tends to move slowly, technologically speaking, and it's easy for us to update test expectations if they do change. Thanks!

2024-04-12 02:17 UTC, Vectornaut commented on doc/logging.md
> +* **"request issue"** – Problem with an HTTP request
The ones in bold are directly generated by Backscope. Can you think of a more conspicuous place to say this in the description text? The place where it's currently said clearly isn't effective.

2024-04-12 02:58 UTC, katestange commented on doc/logging.md
> +* **"request issue"** – Problem with an HTTP request
haha, I think it's me that's not effective.

2024-04-12 05:06 UTC, Vectornaut commented on flaskr/nscope/views.py
> +    ##r = requests.get(match_url).json()
I've dropped all the old code that I could find! Let me know if you find more.

2024-04-12 05:12 UTC, Vectornaut commented on flaskr/nscope/test/test_logging.py
> +class LoggingTest(unittest.TestCase):
I've added all of this stuff to the docs, including Glen's warning about losing logs during a severe incident.

2024-04-12 05:18 UTC, Vectornaut commented
Including the HTTP response dump in the nonexistent sequence test was more annoying than I expected, because parts of the response (the date line and the "last updated" ticker on the OEIS 404 page) are time-dependent. However, I've managed to cut them out, yielding a test that covers at least part of the expected 404 response.

2024-04-12 05:18 UTC, Vectornaut commented
I think this is ready to review again! Could you both try it out, review the issues you brought up, and resolve the conversations that have been addressed to your satisfaction?

2024-04-12 05:31 UTC, gwhitney commented on doc/logging.md
> +```python
Do you need a verb (maybe "is") on the previous line?

2024-04-12 05:33 UTC, gwhitney commented on flaskr/nscope/test/test_logging.py
> +class LoggingTest(unittest.TestCase):
Agree that all my questions were addressed. When Kate's satisfied, she can resolve this item.

2024-04-12 05:39 UTC, gwhitney commented
Oops:
```
backscope> git checkout logbad
Switched to branch 'logbad'
backscope> git pull
[...]
Updating 8893a52..9929fb8
[...]
backscope> sh tools/install-requirements.sh
[...]
Backscope dependencies successfully installed
backscope> flask test
Traceback (most recent call last):
  File "/home/glen/code/backscope/.venv/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/glen/code/backscope/.venv/lib64/python3.11/site-packages/flask/cli.py", line 1064, in main
    cli.main()
  File "/home/glen/code/backscope/.venv/lib64/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/glen/code/backscope/.venv/lib64/python3.11/site-packages/click/core.py", line 1682, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/glen/code/backscope/.venv/lib64/python3.11/site-packages/click/core.py", line 1729, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/glen/code/backscope/.venv/lib64/python3.11/site-packages/flask/cli.py", line 579, in get_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "/home/glen/code/backscope/.venv/lib64/python3.11/site-packages/flask/cli.py", line 313, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/glen/code/backscope/.venv/lib64/python3.11/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File "/home/glen/code/backscope/wsgi.py", line 5, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/home/glen/code/backscope/flaskr/__init__.py", line 129, in create_app
    file_handler = create_file_handler()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/glen/code/backscope/flaskr/__init__.py", line 57, in create_file_handler
    handler = RotatingFileHandler('logs/api.log', maxBytes=2*10**7, backupCount=9)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib64/python3.11/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib64/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/glen/code/backscope/logs/api.log'
```

Does it fail if you have no logs directory and/or no pre-existing api.log file? Needs to be resilient to those possibilities, if so.
Thanks for looking into this!

2024-04-12 05:45 UTC, katestange requested changes
It's possible you forgot to add all the files/directories needed?  Did you move logs into a subdirectory?  When I do `flask run` I get 
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/katestange/data/projects/numberscope/frontscope-backscope/backscope/logs/api.log'
```
and indeed, I have no directory "logs".  `flask test` seems to have a similar problem

2024-04-12 05:45 UTC, katestange commented on doc/logging.md
> +If `log` a log entry, the call
grammar

2024-04-12 05:45 UTC, katestange commented on flaskr/nscope/test/test_logging.py
> +class LoggingTest(unittest.TestCase):
Where is "how to intentionally generate a log entry"? -- I was imagining instructions like, "to see logging in action, delete the existing log files (or make note of the time), load the backend, and try the following URL (blah blah A0000000), then look in the brand new file api.log for an entry that begins with "request issue"...." or something along those lines.

2024-04-12 05:45 UTC, katestange commented on flaskr/nscope/views.py
> +  # start keping track of what's going on
keeping

2024-04-12 07:22 UTC, Vectornaut commented on doc/logging.md
> +If `log` a log entry, the call
Good eye! Fixed.

2024-04-12 07:23 UTC, Vectornaut commented on flaskr/nscope/views.py
> +  # start keping track of what's going on
Another good catch!

2024-04-12 07:50 UTC, Vectornaut commented
I've added instructions on how to manually generate a log entry! Thanks for the reminder.

To make sure that the `logs` directory is always present, with the bonus of ensuring that nothing inside the `logs` directory will accidentally be committed, I've used the [trick](https://stackoverflow.com/a/932982) of populating `logs` with a `.gitignore` file that tells Git to ignore all the other folder contents.

One way to test this mechanism is to remove your `logs` directory before pulling commit 737eabb. The `logs` directory (and the `.gitignore` file inside it) should appear. If you've already pulled the commit, you can instead try removing the log directory and observing that `git` shows a deleted file.

2024-04-12 13:47 UTC, katestange commented on flaskr/nscope/test/test_logging.py
> +class LoggingTest(unittest.TestCase):
I'm happy!

2024-04-12 14:28 UTC, gwhitney commented on doc/logging.md
> +```python
Verb still missing.

2024-04-12 14:49 UTC, katestange approved these changes
It runs nicely on my system now.   I was able to test the "manual" cause a log suggestion.  If Glen is ready to merge, go ahead.

2024-04-12 16:02 UTC, gwhitney commented
I was about to squash and merge but the commit message is all over the place, with all of the commits. @vectornaut could you please write a single cogent commit message for the overall squashed commit? Roughly a one-paragraph overview of the changes wrought by the PR as a whole. You can just put it in a comment here. Then I will squash and merge, using that message. Thanks!

2024-04-12 17:17 UTC, gwhitney commented
(To clarify, the initial comment in this PR is pretty close to what's needed, but I wasn't sure whether any of the comments should be amended in light of the subsequent development of this PR, and  it shouldn't have questions/to-dos; if you feel subsequent changes are still needed, open those points as issues, rather than putting that information into the proposed commit message, which in the end will be hidden away in the git log, which tends only to be consulted when code problems arise.)

2024-04-12 17:33 UTC, gwhitney commented
Took the liberty of adding where to find the log files in production, since it seems on-point for this PR and then will also close #55.

2024-04-12 18:10 UTC, gwhitney commented
And since this now touches server-administration.md, removed warning about get_commit not working to kill #115 too.

2024-04-12 18:11 UTC, Vectornaut commented
> Took the liberty of adding where to find the log files in production

Awesome. I'm almost done with the revised commit message.

2024-04-12 18:44 UTC, Vectornaut commented
Here's my proposed commit message! Let me know if I should shorten it (or feel free to revise it unilaterally). While writing it, I realized that the `current_app.structlogger` attribute should be documented in the documentation, not just in the PR. I made an extra commit to do that.

```
Log request issues

Set up a system to log requests that go wrong. This involves several
smaller changes.

--- Logging ---

Switch to the `structlog` package for all explicit logging. This makes
it easy to write JSON logs that include all the response data from
problematic requests, while also writing summary logs to standard
output.

Add an `oeis_get` wrapper for OEIS requests, which automatically logs
any problems.

Move logs to a new `logs` folder, which is always present because it
contains a tracked `.gitignore` file. Tell Git to ignore log files, to
guard against accidentally checking them into the repository.

--- Testing ---

Add a unit test which just writes a log message.

Revise the end-to-end lookup error test to comfirm that the failed
request is logged as expected. To accomplish this, add facilities for
checking log messages in the abstract endpoint test. These are described
in the comments of `abstract_endpoint_test.py`.
```

2024-04-12 19:09 UTC, gwhitney commented on flaskr/__init__.py
Sorry to raise another issue, but the ordering of imports here is not understandable. In particular, why have you reordered existing imports that did not change? (moving os up and dotenv down, for example)? And why have you abandoned alphabetic order? If there is some other canonical order you are following, please let the reader know with at least a comment, so that when future imports are added/removed, they can be put in the correct places. If there is not, please restore to alphabetic order. Thanks!

2024-04-12 19:10 UTC, Vectornaut commented on flaskr/__init__.py
Oops, didn't realize they were alphabetic before!

2024-04-12 19:13 UTC, gwhitney commented on doc/logging.md
> +<
Please remove whitespace at end of lines and whitespace-only lines (blank lines where needed for clarity are OK, but they should not have whitespace). There are several occurrences throughout this file. Thanks!

2024-04-12 19:14 UTC, gwhitney commented on flaskr/__init__.py
> +  # Add a JSON formatter
Please remove whitespace from blank lines, thanks. (Several occurrences.)  I will look to see if there are any settings on this repo that will make github highlight such things.

2024-04-12 19:15 UTC, Vectornaut commented on doc/logging.md
> +<
Removing trailing whitespace from this file makes sense, since it's new. For existing files where I've added it, maybe a separate PR would make more sense?

2024-04-12 19:15 UTC, gwhitney commented on flaskr/nscope/test/abstract_endpoint_test.py
> +
Ditto about whitespace.

2024-04-12 19:16 UTC, gwhitney commented on flaskr/nscope/test/test_logging.py
> +
Are these blank lines with whitespace something your editor is doing? Please see if you can set it so that blank lines never contain whitespace, thanks.

2024-04-12 19:17 UTC, Vectornaut commented on doc/logging.md
> +<
To clarify: some trailing whitespace comes from previous PRs, and that might deserve its own PR to fix. I'll make sure this PR doesn't introduce any new trailing whitespace, even in existing files.

2024-04-12 19:17 UTC, gwhitney commented on flaskr/nscope/test/test_lookup_errors.py
> +
Oops, another case of invisible whitespace.

2024-04-12 19:18 UTC, gwhitney commented on flaskr/nscope/views.py
I respect that urllib.parse import was in a really weird place. But again, if you are reordering imports anyway, please either make them alphabetical, or if there is some other canonical order, please clarify what it is. Thanks!

2024-04-12 19:19 UTC, gwhitney commented on flaskr/nscope/views.py
> +
Whitespace.

2024-04-12 19:21 UTC, gwhitney commented on doc/logging.md
> +<
Please remove all trailing whitespace/whitespace-only blank lines from any file you touched. That's how source files should be, to avoid these kinds of git-difference noise issues. So as long as you've touched them, we might as well make the whole file conform.

2024-04-12 19:23 UTC, gwhitney commented
My apologies, I saw the odd merge of logbad into logbad in the git log and didn't know what that was all about, so did a "git diff" versus main just to be sure all was well, and all these "noise" items came up which it would be good to squelch here before the merge. Sorry.

2024-04-12 19:27 UTC, Vectornaut commented
> My apologies, I saw the odd merge of logbad into logbad in the git log and didn't know what that was all about

No, it's a good idea to clean these up. Because I'd imagined dealing with formatting errors in a separate commit, I didn't think to make sure this PR didn't introduce new formatting errors. I should be able to finish that in a few minutes.

2024-04-12 19:37 UTC, gwhitney commented on flaskr/__init__.py
> +  # Add a JSON formatter
On github settings to show trailing whitespace: this is a feature that has been requested (https://github.com/orgs/community/discussions/42792) but there has been no response. I upvoted the feature request. Feel free to do so as well. In the meantime, I recommend always doing your own commandline "git diff" before committing. It shows whitespace issues very clearly!

2024-04-12 19:45 UTC, Vectornaut commented
Commit aa5db13 should prevent this PR from introducing new formatting inconsistencies. You may want to review the alphabetization of imports: I tried to imitate existing files, but I'm not sure I did it correctly.

2024-04-12 20:40 UTC, merged