Testing sprout :seedling:
numberscope/backscope pull request #84
Opened 2023-10-19 04:08 UTC by Vectornaut

## Summary

This pull request develops @liammulh's prototype test (`TrivialTest`) into a small suite of useful tests.

## Notable features

* Basic documentation on writing and running tests (`docs/tests.md`).
* A convention for writing families of tests by subclassing an abstract test (in this case, `AbstractEndpointTest`).

## Pitfalls

* The test process fails gracefully when `POSTGRES_DISPOSABLE_DB` is unset or empty, but the code that makes this happen is very convoluted. It ought to be simplified at some point.
* I've changed the definition of `ProdConfig` to accommodate other changes, but I don't know how to make sure production mode still works.

## To do

*See `# TO DO` comments.*

* Expand `AbstractEndpointTest` to test the background work triggered by each endpoint request.

2023-10-20 00:47 UTC, katestange requested changes
I was able to get it up and running and run the tests!  I made some comments on the docs.

2023-10-20 00:47 UTC, katestange commented on doc/tests.md
> +POSTGRES_DISPOSABLE_DB="<disposable database name>"
should this say `export POSTGRES....`?

2023-10-20 00:47 UTC, katestange commented on doc/tests.md
> +
all of these output examples are for two tests that run, not one that skips and one that runs.  perhaps since the current behaviour is that one skips, it should match that

2023-10-20 00:47 UTC, katestange commented on doc/tests.md
> +Tests are kept in the [`flaskr/nscope/test`](../flaskr/nscope/test) directory. The test routine opens at all the files with names matching `test*.py`, pulls out all the classes that descend from `uni
typos: "opens at all" -> "opens all" and "runs the all" -> "runs all the"

2023-10-20 00:47 UTC, katestange commented on flaskr/nscope/test/test_get_oeis_values.py
> +# we end up indexing from zero even if the shift should be nonzero
add a comment that this should be updated when issue # whatever is fixed?  Or maybe a link to this line from the issue about offsets?  not sure what is standard

2023-10-20 00:47 UTC, katestange commented on doc/install-postgres.md
> +POSTGRES_DISPOSABLE_DB="<disposable database name>"
As in other comment, does this need an `export`?

2023-10-20 17:53 UTC, gwhitney commented on flaskr/nscope/test/test_get_oeis_values.py
> +# we end up indexing from zero even if the shift should be nonzero
Also typo "accuarate" => "accurate"

2023-10-20 21:03 UTC, Vectornaut commented on doc/tests.md
> +POSTGRES_DISPOSABLE_DB="<disposable database name>"
This is currently written to match the other lines in the `.env` file, as described in `install-postgres.md`. It works on my system (Ubutnu).

2023-10-20 21:20 UTC, katestange commented on doc/tests.md
> +POSTGRES_DISPOSABLE_DB="<disposable database name>"
weird, on mine I needed the "export" (all the lines in my .env file had this).  Maybe we should say (here and elsewhere) that on some systems it needs the "export"?

2023-10-20 21:50 UTC, Vectornaut commented on doc/install-postgres.md
> +POSTGRES_DISPOSABLE_DB="<disposable database name>"
I don't think so. See reply to previous comment.

2023-10-20 21:50 UTC, gwhitney commented on doc/tests.md
> +POSTGRES_DISPOSABLE_DB="<disposable database name>"
Hmm; I had all exports; but I just removed them all and it worked fine as well. Kate, have you tested whether if you remove all the export keywords, does the backscope work?

2023-10-20 21:55 UTC, katestange commented on doc/tests.md
> +POSTGRES_DISPOSABLE_DB="<disposable database name>"
Oh, hmm, yes I just removed them and it worked fine (just to confirm, I reloaded the virtual environment and ran backscope... do I need to do something else to check this works fine?)

2023-10-20 22:07 UTC, Vectornaut commented on flaskr/nscope/test/test_get_oeis_values.py
> +# we end up indexing from zero even if the shift should be nonzero
I think that's a great idea. I've added remarks to the comment and [the issue](https://github.com/numberscope/backscope/issues/77#issuecomment-1773446190).

2023-10-20 22:12 UTC, Vectornaut commented on doc/tests.md
> +
I've added one example that shows a skipped test. How does it look?

2023-10-20 22:15 UTC, gwhitney commented on doc/tests.md
> +POSTGRES_DISPOSABLE_DB="<disposable database name>"
No, I think that confirms that the exports are not needed, and so it's OK if all of the documentation including this new bit has no "export". Resolving this conversation.

2023-10-20 22:16 UTC, gwhitney commented on .github/workflows/integrate.yml
You need to remove this file from the PR; we agreed we were not doing automated testing as part of this PR.

2023-10-20 22:23 UTC, gwhitney commented on doc/tests.md
> +
(A) Since everything else one does to interact with backscope goes through `manage.py`, (e.g. `python manage.py runserver`), do we want to extend manage.py so you can say `python manage.py  unittest` ? Just a thought/suggestion, not a requirement for this to be merged.

(B) The name "unittest" here is misleading, as it's currently performing (unless I am mistaken) 1 end-to-end test and zero unit tests. I am not saying that there need to be two separate commands for unit tests and end-to-end tests, just that perhaps we should change the command to just "test" or "testsuite" or something?

2023-10-20 22:28 UTC, gwhitney commented
OK, I made a couple of small comments/suggestions, but overall this looks really good! So once Kate's resolved her items and Aaron's had a chance to respond to the things I raised, this should be ready to merge. Thanks, Aaron!

2023-10-20 22:55 UTC, katestange commented on doc/tests.md
> +
nice

2023-10-21 00:37 UTC, Vectornaut commented on doc/tests.md
> +
(A) Sure! I've added a `Manager` command that does this. The documentation now refers to this command, mentioning that you can also call `unittest` directly.

(B) The command `python -m unittest` calls a the built-in [`unittest`](https://docs.python.org/3/library/unittest.html) module from the Python Standard Library. The wrapper command I added to `manage.py` is called `test`, like you suggested.

2023-10-21 00:38 UTC, Vectornaut commented on .github/workflows/integrate.yml
Whoops, I forgot about that!

2023-10-21 16:46 UTC, gwhitney commented on doc/tests.md
> +
Yup, those seem fine. (And yes, I agree we can't change the name of the module in the standard library ;-)

2023-10-21 16:48 UTC, gwhitney commented
OK, as far as I can see, everything is set here for merging. But as Kate has to sign off as the original reviewer, I can't merge on the spot. Kate, when you have a chance, make sure you feel all is well, sign off, and merge. Thanks!

2023-10-21 17:33 UTC, katestange approved these changes

2023-10-21 17:34 UTC, merged